require 'nickel/substitutor'
require 'nickel/nlp_query_constants'

module Nickel
  module Substitutions
    class Standardization
      extend Substitutor
      include NLPQueryConstants

      substitutions do
        # holidays
        sub(/c?h[oa]nn?[aui][ck][ck]?[ua]h?/, 'hannukkah')
        sub(/x-?mas/, 'christmas')
        sub(/st\s+(patrick|patty|pat)s?(\s+day)?/, 'st patricks day')

        # days
        sub(/mondays/, 'every mon')
        sub(/monday/, 'mon')
        sub(/tuesdays/, 'every tue')
        sub(/tuesday/, 'tue')
        sub(/wednesdays/, 'every wed')
        sub(/wednesday/, 'wed')
        sub(/thursdays/, 'every thu')
        sub(/thursday/, 'thu')
        sub(/\bthurs?d?\b/, 'thu')
        sub(/fridays/, 'every fri')
        sub(/friday/, 'fri')
        sub(/saturdays/, 'every sat')
        sub(/saturday/, 'sat')
        sub(/sundays/, 'every sun')
        sub(/sunday/, 'sun')

        # numbers
        sub(/january/, 'jan')
        sub(/february/, 'feb')
        sub(/febr/, 'feb')
        sub(/march/, 'mar')
        sub(/april/, 'apr')
        sub(/may/, 'may')
        sub(/june/, 'jun')
        sub(/july/, 'jul')
        sub(/august/, 'aug')
        sub(/september/, 'sep')
        sub(/sept/, 'sep')
        sub(/october/, 'oct')
        sub(/november/, 'nov')
        sub(/novem/, 'nov')
        sub(/decemb?e?r?/, 'dec')

        # days
        sub(/\bone\s*-?\s*hundred\b/, '100')
        sub(/\bone\s*-?\s*hundredth\b/, '100th')
        sub(/\bninety\s*-?\s*nine\b/, '99')
        sub(/\bninety\s*-?\s*ninth\b/, '99th')
        sub(/\bninety\s*-?\s*eight\b/, '98')
        sub(/\bninety\s*-?\s*eighth\b/, '98th')
        sub(/\bninety\s*-?\s*seven\b/, '97')
        sub(/\bninety\s*-?\s*seventh\b/, '97th')
        sub(/\bninety\s*-?\s*six\b/, '96')
        sub(/\bninety\s*-?\s*sixth\b/, '96th')
        sub(/\bninety\s*-?\s*five\b/, '95')
        sub(/\bninety\s*-?\s*fifth\b/, '95th')
        sub(/\bninety\s*-?\s*four\b/, '94')
        sub(/\bninety\s*-?\s*fourth\b/, '94th')
        sub(/\bninety\s*-?\s*three\b/, '93')
        sub(/\bninety\s*-?\s*third\b/, '93rd')
        sub(/\bninety\s*-?\s*two\b/, '92')
        sub(/\bninety\s*-?\s*second\b/, '92nd')
        sub(/\bninety\s*-?\s*one\b/, '91')
        sub(/\bninety\s*-?\s*first\b/, '91st')
        sub(/\bninety\b/, '90')
        sub(/\bninetieth\b/, '90th')
        sub(/\beighty\s*-?\s*nine\b/, '89')
        sub(/\beighty\s*-?\s*ninth\b/, '89th')
        sub(/\beighty\s*-?\s*eight\b/, '88')
        sub(/\beighty\s*-?\s*eighth\b/, '88th')
        sub(/\beighty\s*-?\s*seven\b/, '87')
        sub(/\beighty\s*-?\s*seventh\b/, '87th')
        sub(/\beighty\s*-?\s*six\b/, '86')
        sub(/\beighty\s*-?\s*sixth\b/, '86th')
        sub(/\beighty\s*-?\s*five\b/, '85')
        sub(/\beighty\s*-?\s*fifth\b/, '85th')
        sub(/\beighty\s*-?\s*four\b/, '84')
        sub(/\beighty\s*-?\s*fourth\b/, '84th')
        sub(/\beighty\s*-?\s*three\b/, '83')
        sub(/\beighty\s*-?\s*third\b/, '83rd')
        sub(/\beighty\s*-?\s*two\b/, '82')
        sub(/\beighty\s*-?\s*second\b/, '82nd')
        sub(/\beighty\s*-?\s*one\b/, '81')
        sub(/\beighty\s*-?\s*first\b/, '81st')
        sub(/\beighty\b/, '80')
        sub(/\beightieth\b/, '80th')
        sub(/\bseventy\s*-?\s*nine\b/, '79')
        sub(/\bseventy\s*-?\s*ninth\b/, '79th')
        sub(/\bseventy\s*-?\s*eight\b/, '78')
        sub(/\bseventy\s*-?\s*eighth\b/, '78th')
        sub(/\bseventy\s*-?\s*seven\b/, '77')
        sub(/\bseventy\s*-?\s*seventh\b/, '77th')
        sub(/\bseventy\s*-?\s*six\b/, '76')
        sub(/\bseventy\s*-?\s*sixth\b/, '76th')
        sub(/\bseventy\s*-?\s*five\b/, '75')
        sub(/\bseventy\s*-?\s*fifth\b/, '75th')
        sub(/\bseventy\s*-?\s*four\b/, '74')
        sub(/\bseventy\s*-?\s*fourth\b/, '74th')
        sub(/\bseventy\s*-?\s*three\b/, '73')
        sub(/\bseventy\s*-?\s*third\b/, '73rd')
        sub(/\bseventy\s*-?\s*two\b/, '72')
        sub(/\bseventy\s*-?\s*second\b/, '72nd')
        sub(/\bseventy\s*-?\s*one\b/, '71')
        sub(/\bseventy\s*-?\s*first\b/, '71st')
        sub(/\bseventy\b/, '70')
        sub(/\bseventieth\b/, '70th')
        sub(/\bsixty\s*-?\s*nine\b/, '69')
        sub(/\bsixty\s*-?\s*ninth\b/, '69th')
        sub(/\bsixty\s*-?\s*eight\b/, '68')
        sub(/\bsixty\s*-?\s*eighth\b/, '68th')
        sub(/\bsixty\s*-?\s*seven\b/, '67')
        sub(/\bsixty\s*-?\s*seventh\b/, '67th')
        sub(/\bsixty\s*-?\s*six\b/, '66')
        sub(/\bsixty\s*-?\s*sixth\b/, '66th')
        sub(/\bsixty\s*-?\s*five\b/, '65')
        sub(/\bsixty\s*-?\s*fifth\b/, '65th')
        sub(/\bsixty\s*-?\s*four\b/, '64')
        sub(/\bsixty\s*-?\s*fourth\b/, '64th')
        sub(/\bsixty\s*-?\s*three\b/, '63')
        sub(/\bsixty\s*-?\s*third\b/, '63rd')
        sub(/\bsixty\s*-?\s*two\b/, '62')
        sub(/\bsixty\s*-?\s*second\b/, '62nd')
        sub(/\bsixty\s*-?\s*one\b/, '61')
        sub(/\bsixty\s*-?\s*first\b/, '61st')
        sub(/\bsixty\b/, '60')
        sub(/\bsixtieth\b/, '60th')
        sub(/\bfifty\s*-?\s*nine\b/, '59')
        sub(/\bfifty\s*-?\s*ninth\b/, '59th')
        sub(/\bfifty\s*-?\s*eight\b/, '58')
        sub(/\bfifty\s*-?\s*eighth\b/, '58th')
        sub(/\bfifty\s*-?\s*seven\b/, '57')
        sub(/\bfifty\s*-?\s*seventh\b/, '57th')
        sub(/\bfifty\s*-?\s*six\b/, '56')
        sub(/\bfifty\s*-?\s*sixth\b/, '56th')
        sub(/\bfifty\s*-?\s*five\b/, '55')
        sub(/\bfifty\s*-?\s*fifth\b/, '55th')
        sub(/\bfifty\s*-?\s*four\b/, '54')
        sub(/\bfifty\s*-?\s*fourth\b/, '54th')
        sub(/\bfifty\s*-?\s*three\b/, '53')
        sub(/\bfifty\s*-?\s*third\b/, '53rd')
        sub(/\bfifty\s*-?\s*two\b/, '52')
        sub(/\bfifty\s*-?\s*second\b/, '52nd')
        sub(/\bfifty\s*-?\s*one\b/, '51')
        sub(/\bfifty\s*-?\s*first\b/, '51st')
        sub(/\bfifty\b/, '50')
        sub(/\bfiftieth\b/, '50th')
        sub(/\bfourty\s*-?\s*nine\b/, '49')
        sub(/\bfourty\s*-?\s*ninth\b/, '49th')
        sub(/\bfourty\s*-?\s*eight\b/, '48')
        sub(/\bfourty\s*-?\s*eighth\b/, '48th')
        sub(/\bfourty\s*-?\s*seven\b/, '47')
        sub(/\bfourty\s*-?\s*seventh\b/, '47th')
        sub(/\bfourty\s*-?\s*six\b/, '46')
        sub(/\bfourty\s*-?\s*sixth\b/, '46th')
        sub(/\bfourty\s*-?\s*five\b/, '45')
        sub(/\bfourty\s*-?\s*fifth\b/, '45th')
        sub(/\bfourty\s*-?\s*four\b/, '44')
        sub(/\bfourty\s*-?\s*fourth\b/, '44th')
        sub(/\bfourty\s*-?\s*three\b/, '43')
        sub(/\bfourty\s*-?\s*third\b/, '43rd')
        sub(/\bfourty\s*-?\s*two\b/, '42')
        sub(/\bfourty\s*-?\s*second\b/, '42nd')
        sub(/\bfourty\s*-?\s*one\b/, '41')
        sub(/\bfourty\s*-?\s*first\b/, '41st')
        sub(/\bfourty\b/, '40')
        sub(/\bfourtieth\b/, '40th')
        sub(/\bthirty\s*-?\s*nine\b/, '39')
        sub(/\bthirty\s*-?\s*ninth\b/, '39th')
        sub(/\bthirty\s*-?\s*eight\b/, '38')
        sub(/\bthirty\s*-?\s*eighth\b/, '38th')
        sub(/\bthirty\s*-?\s*seven\b/, '37')
        sub(/\bthirty\s*-?\s*seventh\b/, '37th')
        sub(/\bthirty\s*-?\s*six\b/, '36')
        sub(/\bthirty\s*-?\s*sixth\b/, '36th')
        sub(/\bthirty\s*-?\s*five\b/, '35')
        sub(/\bthirty\s*-?\s*fifth\b/, '35th')
        sub(/\bthirty\s*-?\s*four\b/, '34')
        sub(/\bthirty\s*-?\s*fourth\b/, '34th')
        sub(/\bthirty\s*-?\s*three\b/, '33')
        sub(/\bthirty\s*-?\s*third\b/, '33rd')
        sub(/\bthirty\s*-?\s*two\b/, '32')
        sub(/\bthirty\s*-?\s*second\b/, '32nd')
        sub(/\bthirty\s*-?\s*one\b/, '31')
        sub(/\bthirty\s*-?\s*first\b/, '31st')
        sub(/\bthirty\b/, '30')
        sub(/\bthirtieth\b/, '30th')
        sub(/\btwenty\s*-?\s*nine\b/, '29')
        sub(/\btwenty\s*-?\s*ninth\b/, '29th')
        sub(/\btwenty\s*-?\s*eight\b/, '28')
        sub(/\btwenty\s*-?\s*eighth\b/, '28th')
        sub(/\btwenty\s*-?\s*seven\b/, '27')
        sub(/\btwenty\s*-?\s*seventh\b/, '27th')
        sub(/\btwenty\s*-?\s*six\b/, '26')
        sub(/\btwenty\s*-?\s*sixth\b/, '26th')
        sub(/\btwenty\s*-?\s*five\b/, '25')
        sub(/\btwenty\s*-?\s*fifth\b/, '25th')
        sub(/\btwenty\s*-?\s*four\b/, '24')
        sub(/\btwenty\s*-?\s*fourth\b/, '24th')
        sub(/\btwenty\s*-?\s*three\b/, '23')
        sub(/\btwenty\s*-?\s*third\b/, '23rd')
        sub(/\btwenty\s*-?\s*two\b/, '22')
        sub(/\btwenty\s*-?\s*second\b/, '22nd')
        sub(/\btwenty\s*-?\s*one\b/, '21')
        sub(/\btwenty\s*-?\s*first\b/, '21st')
        sub(/\btwenty\b/, '20')
        sub(/\btwentieth\b/, '20th')
        sub(/\bnineteen\b/, '19')
        sub(/\bnineteenth\b/, '19th')
        sub(/\beighteen\b/, '18')
        sub(/\beighteenth\b/, '18th')
        sub(/\bseventeen\b/, '17')
        sub(/\bseventeenth\b/, '17th')
        sub(/\bsixteen\b/, '16')
        sub(/\bsixteenth\b/, '16th')
        sub(/\bfifteen\b/, '15')
        sub(/\bfifteenth\b/, '15th')
        sub(/\bfourteen\b/, '14')
        sub(/\bfourteenth\b/, '14th')
        sub(/\bthirteen/, '13')
        sub(/\bthirteenth/, '13th')
        sub(/\btwelve\b/, '12')
        sub(/\btwelfth\b/, '12th')
        sub(/\beleven\b/, '11')
        sub(/\beleventh\b/, '11th')
        sub(/\bten\b/, '10')
        sub(/\btenth\b/, '10th')
        sub(/\bnine\b/, '9')
        sub(/\bninth\b/, '9th')
        sub(/\beight\b/, '8')
        sub(/\beighth\b/, '8th')
        sub(/\bseven\b/, '7')
        sub(/\bseventh\b/, '7th')
        sub(/\bsix\b/, '6')
        sub(/\bsixth\b/, '6th')
        sub(/\bfive\b/, '5')
        sub(/\bfifth\b/, '5th')
        sub(/\bfour\b/, '4')
        sub(/\bfourth\b/, '4th')
        sub(/\bthree\b/, '3')
        sub(/\bthird\b/, '3rd')
        sub(/\btwo\b/, '2')
        sub(/\bsecond\b/, '2nd')
        sub(/\bone\b/, '1')
        sub(/\bfirst\b/, '1st')
        sub(/\bzero\b/, '0')
        sub(/\bzeroth\b/, '0th')

        # times
        sub(/([0-9])(?:\s*)a\b/, '\1am')  # allows 5a as 5am
        sub(/([0-9])(?:\s*)p\b/, '\1pm')  # allows 5p as 5pm
        sub(/\s+am\b/, 'am')  # removes any spaces before am, shouldn't I check for preceeding digits?
        sub(/\s+pm\b/, 'pm')  # removes any spaces before pm, shouldn't I check for preceeding digits?

        # miscellaneous
        sub(/last\s+#{DAY_OF_WEEK.source}/, '5th \1')     # last dayname  =>  5th dayname
        sub(/\ba\s+(week|month|day)/, '1 \1')     # a month|week|day  =>  1 month|week|day
        sub(/^(through|until)/, 'today through')   # ^through  =>  today through
        sub(/every\s*(night|morning)/, 'every day')
        sub(/tonight/, 'today')
        sub(/this(?:\s*)morning/, 'today')
        sub(/before\s+12pm/, '6am to 12pm')        # arbitrary
      end
    end
  end
end
